## Пример: Кластеризация текстов

### Выборка

In [80]:
import numpy as np


In [11]:
from sklearn.datasets import fetch_20newsgroups
train_all = fetch_20newsgroups(subset="train")
print(train_all.target_names)

['alt.atheism', 'comp.graphics', 'comp.os.ms-windows.misc', 'comp.sys.ibm.pc.hardware', 'comp.sys.mac.hardware', 'comp.windows.x', 'misc.forsale', 'rec.autos', 'rec.motorcycles', 'rec.sport.baseball', 'rec.sport.hockey', 'sci.crypt', 'sci.electronics', 'sci.med', 'sci.space', 'soc.religion.christian', 'talk.politics.guns', 'talk.politics.mideast', 'talk.politics.misc', 'talk.religion.misc']


In [13]:
simple_dataset = fetch_20newsgroups(subset="train", categories=['comp.sys.mac.hardware', 'soc.religion.christian', 'rec.sport.hockey'])

In [21]:
print(simple_dataset.data[-1])

From: dlecoint@garnet.acns.fsu.edu (Darius_Lecointe)
Subject: Re: Sabbath Admissions 5of5
Organization: Florida State University
Lines: 21

I find it interesting that cls never answered any of the questions posed. 
Then he goes on the make statements which make me shudder.  He has
established a two-tiered God.  One set of rules for the Jews (his people)
and another set for the saved Gentiles (his people).  Why would God
discriminate?  Does the Jew who accepts Jesus now have to live under the
Gentile rules.

God has one set of rules for all his people.  Paul was never against the
law.  In fact he says repeatedly that faith establishes rather that annuls
the law.  Paul's point is germane to both Jews and Greeks.  The Law can
never be used as an instrument of salvation.  And please do not combine
the ceremonial and moral laws in one.

In Matt 5:14-19 Christ plainly says what He came to do and you say He was
only saying that for the Jews's benefit.  Your Christ must be a
politician, speaki

In [22]:
print(simple_dataset.data[-2])

From: scialdone@nssdca.gsfc.nasa.gov (John Scialdone)
Subject: CUT Vukota and Pilon!!!
News-Software: VAX/VMS VNEWS 1.41    
Organization: NASA - Goddard Space Flight Center
Lines: 32

I have been to all 3 Isles/Caps tilts at the Crap Centre this year, all Isles
wins and there is no justification for Vukota and Pilon to play for the Isles.
Vukota is absolutely the worst puck handler in the world!! He couldn't hit a
bull in the ass with a banjo!! Al must remember a few years back when Mick 
scored 3 goals in one period against the Caps in a 5-3 Isles win. I was there
and was astonished as was the rest of the crowd. Wake-up Al!!! Years later he's
gotten worse. He's a cheap shot artist and always ends up getting
stupid/senseless penalties. I think he would make a good police officier!!!

As for Pilon, he can't carry the puck out to center ice by himself. He either
makes a bad pass resulting in a turnover, or he attempts to bring the puck 
towards the neutral zone and skates right into an 

In [20]:
simple_dataset.target

array([0, 0, 1, ..., 0, 1, 2], dtype=int64)

In [25]:
len(simple_dataset.data)

1777

### Признаки

In [49]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
vectorizer = TfidfVectorizer(max_df=500, min_df=10)
matrix = vectorizer.fit_transform(simple_dataset.data)

In [44]:
print(matrix.shape)

(1777, 333)


### Агломеративная кластеризация (neighbour joining)

In [51]:
from sklearn.cluster import AgglomerativeClustering

model = AgglomerativeClustering(n_clusters=3, affinity="cosine", linkage="complete")
preds = model.fit_predict(matrix.toarray())

In [52]:
print(list(preds))

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [56]:
print(matrix[0])

  (0, 877)	0.111806579628099
  (0, 880)	0.11851815596020333
  (0, 2243)	0.0925317447411647
  (0, 1136)	0.05005067187805151
  (0, 2358)	0.08407975300726757
  (0, 2820)	0.10804290934262964
  (0, 2108)	0.12357635170024023
  (0, 3035)	0.10154477899829953
  (0, 1229)	0.07360450638969387
  (0, 3262)	0.13021297950442332
  (0, 1366)	0.0836339497399446
  (0, 3305)	0.06783179408623191
  (0, 551)	0.09781400308186793
  (0, 1961)	0.22885999498507148
  (0, 619)	0.1704733433340938
  (0, 294)	0.051771062722228284
  (0, 3322)	0.09538902048354801
  (0, 2325)	0.05419206470797136
  (0, 620)	0.111806579628099
  (0, 1831)	0.1250526461821779
  (0, 3285)	0.11264581593118288
  (0, 2422)	0.09427236106959616
  (0, 301)	0.05563256696046784
  (0, 855)	0.20162554088271675
  (0, 2868)	0.08596208970791507
  :	:
  (0, 900)	0.12357635170024023
  (0, 354)	0.06947437383545056
  (0, 2048)	0.07488448956033757
  (0, 1991)	0.07113027685860011
  (0, 926)	0.11742059318548874
  (0, 3722)	0.09501028877632493
  (0, 1905)	0.081735

In [58]:
vectorizer.get_feature_names()[877]

'connect'

In [60]:
"connect" in simple_dataset.data[0]

True

## K_Means

In [62]:
from sklearn.cluster import KMeans

model = KMeans(n_clusters=3, random_state=42)
preds = model.fit_predict(matrix.toarray())
print(preds)

[0 0 2 ... 0 2 1]


In [64]:
print(simple_dataset.target)

[0 0 1 ... 0 1 2]


In [68]:
mapping = {2: 1, 1: 2, 0: 0}
mapped_preds = [mapping[pred] for pred in preds]
print(float(sum(mapped_preds != simple_dataset.target)) / len(simple_dataset.target))

0.04614518851997749


In [70]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score
clf = LogisticRegression()
print(cross_val_score(clf, matrix, simple_dataset.target).mean())

0.9859313182465581


### Более сложная выборка

In [71]:
train_all.target_names

['alt.atheism',
 'comp.graphics',
 'comp.os.ms-windows.misc',
 'comp.sys.ibm.pc.hardware',
 'comp.sys.mac.hardware',
 'comp.windows.x',
 'misc.forsale',
 'rec.autos',
 'rec.motorcycles',
 'rec.sport.baseball',
 'rec.sport.hockey',
 'sci.crypt',
 'sci.electronics',
 'sci.med',
 'sci.space',
 'soc.religion.christian',
 'talk.politics.guns',
 'talk.politics.mideast',
 'talk.politics.misc',
 'talk.religion.misc']

In [72]:
dataset = fetch_20newsgroups(subset="train", categories=['comp.sys.mac.hardware', 'comp.os.ms-windows.misc', 'comp.graphics'])

In [74]:
matrix = vectorizer.fit_transform(dataset.data)
model = KMeans(n_clusters=3, random_state=42)
preds = model.fit_predict(matrix.toarray())
print(preds)
print(dataset.target)

[2 1 0 ... 2 0 2]
[2 1 1 ... 2 0 2]


In [110]:
print(sum(np.not_equal(preds,  dataset.target)) / len(dataset.target))

0.23217341699942956


In [111]:
clf = LogisticRegression()
print(cross_val_score(clf, matrix, dataset.target).mean())

0.9264143264143264


### SVD + KMeans

In [113]:
from sklearn.decomposition import TruncatedSVD

model = KMeans(n_clusters=3, random_state=42)
svd = TruncatedSVD(n_components=1000, random_state=123)
features = svd.fit_transform(matrix)
preds = model.fit_predict(features)
print(preds)
print(dataset.target)

[0 2 1 ... 0 1 0]
[2 1 1 ... 2 0 2]


In [115]:
mapping = {2: 1, 1: 0, 0: 2}
mapped_preds = [mapping[pred] for pred in preds]
print(sum(mapped_preds != dataset.target) / len(dataset.target))

0.2065031374786081


In [116]:
from sklearn.decomposition import TruncatedSVD

model = KMeans(n_clusters=3, random_state=42)
svd = TruncatedSVD(n_components=200, random_state=123)
features = svd.fit_transform(matrix)
preds = model.fit_predict(features)
print(preds)
print(dataset.target)

[2 0 1 ... 2 1 2]
[2 1 1 ... 2 0 2]


In [120]:
import itertools
def validate_with_mapping(preds, target):
    permutation = itertools.permutations([0, 1, 2])
    for a, b, c in permutation:
        mapping = {2: a, 1: b, 0: c}
        mapped_preds = [mapping[pred] for pred in preds]
        print(sum(mapped_preds != target) / len(target))
validate_with_mapping(preds, dataset.target)

0.9007415858528237
0.6742726754135767
0.7056474614945807
0.8938961779806047
0.2053622361665716
0.6200798630918426


In [121]:
model = KMeans(n_clusters=3, random_state=42)
svd = TruncatedSVD(n_components=200, random_state=321)
features = svd.fit_transform(matrix)
preds = model.fit_predict(features)
print(preds)
print(dataset.target)
validate_with_mapping(preds, dataset.target)

[2 1 0 ... 2 0 2]
[2 1 1 ... 2 0 2]
0.713063320022818
0.845407872219053
0.8893325727324587
0.7005134055904164
0.5864232743867656
0.2652595550484883


### Итоги

1. Получили интерпретируемый результат на обеих выборках
2. Реальность, однако, намного более жестка
3. Попробовали использовать AgglomerativeClustering и KMeans